// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH3-9M839vX0ewtUIOlzkQ_1eWEns4XL4',
    appId: '1:369080695601:web:0093f467deba16a10d4e10',
    messagingSenderId: '369080695601',
    projectId: 'mealprepapp-ad0af',
    authDomain: 'mealprepapp-ad0af.firebaseapp.com',
    storageBucket: 'mealprepapp-ad0af.firebasestorage.app',
    measurementId: 'G-KJ3BDHPVL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJBYhyxj7_c3jpjTa1-tNIDZ77se3Tfo',
    appId: '1:369080695601:android:e4c78706500763ef0d4e10',
    messagingSenderId: '369080695601',
    projectId: 'mealprepapp-ad0af',
    storageBucket: 'mealprepapp-ad0af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjMJ1z6l3VfiKeQJ_lIbSJGlv9BxBk0M0',
    appId: '1:369080695601:ios:eb056d1a171ddbae0d4e10',
    messagingSenderId: '369080695601',
    projectId: 'mealprepapp-ad0af',
    storageBucket: 'mealprepapp-ad0af.firebasestorage.app',
    iosBundleId: 'com.example.mealPrepareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjMJ1z6l3VfiKeQJ_lIbSJGlv9BxBk0M0',
    appId: '1:369080695601:ios:eb056d1a171ddbae0d4e10',
    messagingSenderId: '369080695601',
    projectId: 'mealprepapp-ad0af',
    storageBucket: 'mealprepapp-ad0af.firebasestorage.app',
    iosBundleId: 'com.example.mealPrepareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH3-9M839vX0ewtUIOlzkQ_1eWEns4XL4',
    appId: '1:369080695601:web:d48bc89696e67b170d4e10',
    messagingSenderId: '369080695601',
    projectId: 'mealprepapp-ad0af',
    authDomain: 'mealprepapp-ad0af.firebaseapp.com',
    storageBucket: 'mealprepapp-ad0af.firebasestorage.app',
    measurementId: 'G-FJ1M48SBE5',
  );
}